export const items = {
  projects: [
    {
      id: 1,
      title: "Trek Diaries",
      desc: "Trek Diaries is a social media site that is well-designed to meet the needs of trek and hike enthusiasts, making it a must-have platform in today's world. The website facilitates the exploration of new locations, connects with like-minded individuals, and shares experiences through posts, likes, and comments. ",
      img: "/TDs.jpg",
      linked: "https://trek-diaries-bc0ax3h4n-trekdiaries123.vercel.app/login?from=%2F",
    },
    {
      id: 2,
      title: "Trek Diaries Mobile App",
      desc: "Trek Diaries is a social media app that is well-designed to meet the needs of trek and hike enthusiasts, making it a must-have app in today's world. The app facilitates the exploration of new locations, connects with like-minded individuals, and shares experiences through posts, likes, and comments. ",
      img: "/trekapp.png",
      linked: "https://github.com/Re-Dei-s-Organization/Trek-Diaries-Mobile",
    },
    {
      id: 3,
      title: "Battleship",
      desc: "Battleship also known as Sea Battle is a classic strategy type guessing game for multiplayer which is played online in a browser on which each player`s fleet of warships are marked. The locations of the fleets are hidden from the other player. Players alternate turns at the other player`s ships, and the objective of the game is to destroy the opposing player`s fleet.",
      img: "/Battleship.jpg",
      linked: "https://battleship-io.onrender.com",
    },
    {
      id: 4,
      title: "Chat Message",
      desc: "Real time chat applications have become an essential part of the digital world, enabling people to communicate with each other smoothly and continuously from anywhere and anytime. In this project, we have developed real-time chat application, `chat-JPT` using Socket.io and Node.js.",
      img: "/chatapp.png",
      linked: "https://github.com/Re-Dei-s-Organization/chat-JPT",
    },
    {
      id: 5,
      title: "Gas Leakage Detection System",
      desc: "The Gas Leak Detection System is designed to detect the presence of leakage of gas in the environment using a gas sensor. When a gas leak is detected, the system triggers an audible alarm, displays a warning message on an LCD screen, and activates an LED indicator to signal the detection. The project aims to enhance safety by providing an early warning system to prevent potential accidents.",
      img: "/detected.jpg",
      linked: "https://github.com/Shashanka10/Gas_Leak_Detection_System",
    },
    {
      id: 6,
      title: "CureMe",
      desc: "CureMe is a doctor appointment booking platform that allows users to conveniently select a doctor, choose from available time slots and days, and book appointments with ease. With CureMe, patients can find medical professionals across various specialties and enjoy a smooth, efficient booking experience.",
      img: "/cureme.png",
      linked: "https://cureme.vercel.app/",
    },
    {
      id: 7,
      title: "Maze Runner 2D Simulation game",
      desc: "It is a fun and engaging 2D simulation car game developed using python, pygame, and pyopengl. A player has to drive a car through a complex maze to the finish line.",
      img: "/mazerunner.jpg",
      linked: "https://github.com/Shashanka10/OpenGL-Project",
    },
    {
      id: 8,
      title: "Roller Ball game",
      desc: "It is an action-packed ball game where the player controls a ball that must collect pickups to score points while avoiding enemies. Colliding with an enemy ends the game, but collecting 9 or more pickups wins the game.",
      img: "/rollerball.png",
      linked: "https://shashanka10.itch.io/roller-baller",
    },
  ],
  blogs: [
    {
      id: 1,
      title: "10 Must-Have VS Code Extensions for Developers in 2025",
      desc: "Visual Studio Code (VS Code) is one of the most popular code editors today, thanks to its flexibility, speed, and rich extension ecosystem. Whether you’re a frontend developer, backend engineer, or DevOps specialist, the right extensions can supercharge your productivity.",
      img: "/vscode.jpg",
      linked: "https://medium.com/@shashanka10/10-must-have-vs-code-extensions-for-developers-in-2025-c5a27e8deee1",
    },
    {
      id: 2,
      title: "We All Know GitHub, But Have You Heard of Bitbucket, Jira and Jenkins?",
      desc: "Why is GitHub the default for so many students, while Jira and Bitbucket — despite being powerful — feel like corporate labyrinths? Let’s break it down.",
      img: "/bitbuck.jpg",
      linked: "https://medium.com/@shashanka10/we-all-know-github-but-have-you-heard-of-bitbucket-jira-and-jenkins-e3776d8313d2",
    },
    {
      id: 3,
      title: "Standup: The 15-Minute Secret to a More Productive Team",
      desc: "In today’s fast-paced work environment, teams are expected to be agile, adaptable, and responsive to changes in real-time. The pressure to stay on track with projects, meet deadlines, and collaborate effectively can be overwhelming. But what if there was a simple way to boost team productivity, enhance communication, and keep everyone on the same page? Enter the standup meeting: a brief, but incredibly effective tool for driving team productivity.",
      img: "/sprint.jpg",
      linked: "https://medium.com/@shashanka10/standup-the-15-minute-secret-to-a-more-productive-team-0c1bbfd98beb",
    },
        {
      id: 4,
      title: "Yopmail: The Ultimate Disposable Email Service for Privacy and Convenience",
      desc: "In today’s digital world, signing up for online services often requires an email address. But what if you don’t want to use your personal or work email to avoid spam, newsletters, or potential data breaches? That’s where Yopmail comes in.",
      img: "/yop.png",
      linked: "https://medium.com/@shashanka10/yopmail-the-ultimate-disposable-email-service-for-privacy-and-convenience-602ebd177d1d",
    },
    {
      id: 5,
      title: "A Beginner’s Guide to Swagger: Simplifying API Documentation and Testing",
      desc: "APIs (Application Programming Interfaces) are the backbone of modern software development. But let’s face it — poor API documentation can make even the best-built APIs frustrating to use. That’s where Swagger steps in.",
      img: "/swag.png",
      linked: "https://medium.com/@shashanka10/a-beginners-guide-to-swagger-simplifying-api-documentation-and-testing-55bf804e138d",
    },
    {
      id: 6,
      title: "QA vs. Developers: Breaking the Toxic Cycle for Better Software",
      desc: "This blog explores the evolving relationship between QA and developers, why conflicts arise, and how both can work together to ship better software, faster.",
      img: "/dev.png",
      linked: "https://medium.com/@shashanka10/qa-vs-developers-breaking-the-toxic-cycle-for-better-software-375485e1ed02",
    },
  ],
  researchs: [
    {
      id: 1,
      title: "Digital Health in Nepal: Past, Current and Future Scenarios",
      desc: "This paper explores the evolution of digital health in Nepal, from its early days in the 1990s with the Health Management Information System (HMIS) to current implementations like IHIMS and DHIS2.",
      img: "/digitalhealth.jpg",
      linked: "https://www.researchgate.net/publication/401330627_Digital_Health_in_Nepal_Past_Current_and_Future_Scenarios",
    },
    {
      id: 2,
      title: "Ethics of Modern Media Provocation",
      desc: "This study examines the ethical implications of modern media provocation, with a specific focus on rage-baiting, a strategy that deliberately provokes strong emotional responses through sensationalized and divisive content to increase engagement in digital platforms.",
      img: "/ragebait.jpg",
      linked: "https://www.researchgate.net/publication/401331932_Ethics_of_Modern_Media_Provocation",
    },
  ],
};
